
const forestData = [
    //青藏
    {
        "2000": [{
            "name": "西宁",
            "value": "165390"
        }, {
            "name": "海东",
            "value": "203683"
        }, {
            "name": "海北",
            "value": "523888"
        }, {
            "name": "海南",
            "value": "293727"
        }, {
            "name": "黄南",
            "value": "338928"
        }, {
            "name": "果洛",
            "value": "593785"
        }, {
            "name": "玉树",
            "value": "440723"
        }, {
            "name": "海西",
            "value": "327578"
        }, {
            "name": "拉萨",
            "value": "128831"
        }, {
            "name": "昌都",
            "value": "2818447"
        }, {
            "name": "山南",
            "value": "3006141"
        }, {
            "name": "日喀则",
            "value": "262424"
        }, {
            "name": "那曲",
            "value": "290511"
        }, {
            "name": "阿里",
            "value": "17073"
        }, {
            "name": "林芝",
            "value": "5927842"
        }],
        "2001": [{
            "name": "西宁",
            "value": "165338.6"
        }, {
            "name": "海东",
            "value": "203699.4"
        }, {
            "name": "海北",
            "value": "523844.8"
        }, {
            "name": "海南",
            "value": "293648.6"
        }, {
            "name": "黄南",
            "value": "338799.8"
        }, {
            "name": "果洛",
            "value": "593748.2"
        }, {
            "name": "玉树",
            "value": "440731.4"
        }, {
            "name": "海西",
            "value": "327507.4"
        }, {
            "name": "拉萨",
            "value": "128826.2"
        }, {
            "name": "昌都",
            "value": "2818447"
        }, {
            "name": "山南",
            "value": "3006140.8"
        }, {
            "name": "日喀则",
            "value": "262423.6"
        }, {
            "name": "那曲",
            "value": "290511"
        }, {
            "name": "阿里",
            "value": "17073"
        }, {
            "name": "林芝",
            "value": "5927912.8"
        }],
        "2002": [{
            "name": "西宁",
            "value": "165287.2"
        }, {
            "name": "海东",
            "value": "203715.8"
        }, {
            "name": "海北",
            "value": "523801.6"
        }, {
            "name": "海南",
            "value": "293570.2"
        }, {
            "name": "黄南",
            "value": "338671.6"
        }, {
            "name": "果洛",
            "value": "593711.4"
        }, {
            "name": "玉树",
            "value": "440739.8"
        }, {
            "name": "海西",
            "value": "327436.8"
        }, {
            "name": "拉萨",
            "value": "128821.4"
        }, {
            "name": "昌都",
            "value": "2818447"
        }, {
            "name": "山南",
            "value": "3006140.6"
        }, {
            "name": "日喀则",
            "value": "262423.2"
        }, {
            "name": "那曲",
            "value": "290511"
        }, {
            "name": "阿里",
            "value": "17073"
        }, {
            "name": "林芝",
            "value": "5927983.6"
        }],
        "2003": [{
            "name": "西宁",
            "value": "165235.8"
        }, {
            "name": "海东",
            "value": "203732.2"
        }, {
            "name": "海北",
            "value": "523758.4"
        }, {
            "name": "海南",
            "value": "293491.8"
        }, {
            "name": "黄南",
            "value": "338543.4"
        }, {
            "name": "果洛",
            "value": "593674.6"
        }, {
            "name": "玉树",
            "value": "440748.2"
        }, {
            "name": "海西",
            "value": "327366.2"
        }, {
            "name": "拉萨",
            "value": "128816.6"
        }, {
            "name": "昌都",
            "value": "2818447"
        }, {
            "name": "山南",
            "value": "3006140.4"
        }, {
            "name": "日喀则",
            "value": "262422.8"
        }, {
            "name": "那曲",
            "value": "290511"
        }, {
            "name": "阿里",
            "value": "17073"
        }, {
            "name": "林芝",
            "value": "5928054.4"
        }],
        "2004": [{
            "name": "西宁",
            "value": "165184.4"
        }, {
            "name": "海东",
            "value": "203748.6"
        }, {
            "name": "海北",
            "value": "523715.2"
        }, {
            "name": "海南",
            "value": "293413.4"
        }, {
            "name": "黄南",
            "value": "338415.2"
        }, {
            "name": "果洛",
            "value": "593637.8"
        }, {
            "name": "玉树",
            "value": "440756.6"
        }, {
            "name": "海西",
            "value": "327295.6"
        }, {
            "name": "拉萨",
            "value": "128811.8"
        }, {
            "name": "昌都",
            "value": "2818447"
        }, {
            "name": "山南",
            "value": "3006140.2"
        }, {
            "name": "日喀则",
            "value": "262422.4"
        }, {
            "name": "那曲",
            "value": "290511"
        }, {
            "name": "阿里",
            "value": "17073"
        }, {
            "name": "林芝",
            "value": "5928125.2"
        }],
        "2005": [{
            "name": "西宁",
            "value": "165133"
        }, {
            "name": "海东",
            "value": "203765"
        }, {
            "name": "海北",
            "value": "523672"
        }, {
            "name": "海南",
            "value": "293335"
        }, {
            "name": "黄南",
            "value": "338287"
        }, {
            "name": "果洛",
            "value": "593601"
        }, {
            "name": "玉树",
            "value": "440765"
        }, {
            "name": "海西",
            "value": "327225"
        }, {
            "name": "拉萨",
            "value": "128807"
        }, {
            "name": "昌都",
            "value": "2818447"
        }, {
            "name": "山南",
            "value": "3006140"
        }, {
            "name": "日喀则",
            "value": "262422"
        }, {
            "name": "那曲",
            "value": "290511"
        }, {
            "name": "阿里",
            "value": "17073"
        }, {
            "name": "林芝",
            "value": "5928196"
        }],
        "2006": [{
            "name": "西宁",
            "value": "165167.8"
        }, {
            "name": "海东",
            "value": "203760.4"
        }, {
            "name": "海北",
            "value": "523667.2"
        }, {
            "name": "海南",
            "value": "293325.2"
        }, {
            "name": "黄南",
            "value": "338286.6"
        }, {
            "name": "果洛",
            "value": "593585.6"
        }, {
            "name": "玉树",
            "value": "440704.6"
        }, {
            "name": "海西",
            "value": "327239.8"
        }, {
            "name": "拉萨",
            "value": "128806"
        }, {
            "name": "昌都",
            "value": "2818447"
        }, {
            "name": "山南",
            "value": "3006140"
        }, {
            "name": "日喀则",
            "value": "262421.2"
        }, {
            "name": "那曲",
            "value": "290511"
        }, {
            "name": "阿里",
            "value": "17073"
        }, {
            "name": "林芝",
            "value": "5928196.2"
        }],
        "2007": [{
            "name": "西宁",
            "value": "165202.6"
        }, {
            "name": "海东",
            "value": "203755.8"
        }, {
            "name": "海北",
            "value": "523662.4"
        }, {
            "name": "海南",
            "value": "293315.4"
        }, {
            "name": "黄南",
            "value": "338286.2"
        }, {
            "name": "果洛",
            "value": "593570.2"
        }, {
            "name": "玉树",
            "value": "440644.2"
        }, {
            "name": "海西",
            "value": "327254.6"
        }, {
            "name": "拉萨",
            "value": "128805"
        }, {
            "name": "昌都",
            "value": "2818447"
        }, {
            "name": "山南",
            "value": "3006140"
        }, {
            "name": "日喀则",
            "value": "262420.4"
        }, {
            "name": "那曲",
            "value": "290511"
        }, {
            "name": "阿里",
            "value": "17073"
        }, {
            "name": "林芝",
            "value": "5928196.4"
        }],
        "2008": [{
            "name": "西宁",
            "value": "165237.4"
        }, {
            "name": "海东",
            "value": "203751.2"
        }, {
            "name": "海北",
            "value": "523657.6"
        }, {
            "name": "海南",
            "value": "293305.6"
        }, {
            "name": "黄南",
            "value": "338285.8"
        }, {
            "name": "果洛",
            "value": "593554.8"
        }, {
            "name": "玉树",
            "value": "440583.8"
        }, {
            "name": "海西",
            "value": "327269.4"
        }, {
            "name": "拉萨",
            "value": "128804"
        }, {
            "name": "昌都",
            "value": "2818447"
        }, {
            "name": "山南",
            "value": "3006140"
        }, {
            "name": "日喀则",
            "value": "262419.6"
        }, {
            "name": "那曲",
            "value": "290511"
        }, {
            "name": "阿里",
            "value": "17073"
        }, {
            "name": "林芝",
            "value": "5928196.6"
        }],
        "2009": [{
            "name": "西宁",
            "value": "165272.2"
        }, {
            "name": "海东",
            "value": "203746.6"
        }, {
            "name": "海北",
            "value": "523652.8"
        }, {
            "name": "海南",
            "value": "293295.8"
        }, {
            "name": "黄南",
            "value": "338285.4"
        }, {
            "name": "果洛",
            "value": "593539.4"
        }, {
            "name": "玉树",
            "value": "440523.4"
        }, {
            "name": "海西",
            "value": "327284.2"
        }, {
            "name": "拉萨",
            "value": "128803"
        }, {
            "name": "昌都",
            "value": "2818447"
        }, {
            "name": "山南",
            "value": "3006140"
        }, {
            "name": "日喀则",
            "value": "262418.8"
        }, {
            "name": "那曲",
            "value": "290511"
        }, {
            "name": "阿里",
            "value": "17073"
        }, {
            "name": "林芝",
            "value": "5928196.8"
        }],
        "2010": [{
            "name": "西宁",
            "value": "165307"
        }, {
            "name": "海东",
            "value": "203742"
        }, {
            "name": "海北",
            "value": "523648"
        }, {
            "name": "海南",
            "value": "293286"
        }, {
            "name": "黄南",
            "value": "338285"
        }, {
            "name": "果洛",
            "value": "593524"
        }, {
            "name": "玉树",
            "value": "440463"
        }, {
            "name": "海西",
            "value": "327299"
        }, {
            "name": "拉萨",
            "value": "128802"
        }, {
            "name": "昌都",
            "value": "2818447"
        }, {
            "name": "山南",
            "value": "3006140"
        }, {
            "name": "日喀则",
            "value": "262418"
        }, {
            "name": "那曲",
            "value": "290511"
        }, {
            "name": "阿里",
            "value": "17073"
        }, {
            "name": "林芝",
            "value": "5928197"
        }],
        "2011": [{
            "name": "西宁",
            "value": "165281.6"
        }, {
            "name": "海东",
            "value": "203728.8"
        }, {
            "name": "海北",
            "value": "523266"
        }, {
            "name": "海南",
            "value": "293281.2"
        }, {
            "name": "黄南",
            "value": "338270.6"
        }, {
            "name": "果洛",
            "value": "593504.8"
        }, {
            "name": "玉树",
            "value": "440451.8"
        }, {
            "name": "海西",
            "value": "327239.8"
        }, {
            "name": "拉萨",
            "value": "128740.6"
        }, {
            "name": "昌都",
            "value": "2818440.2"
        }, {
            "name": "山南",
            "value": "3006051.4"
        }, {
            "name": "日喀则",
            "value": "262458.2"
        }, {
            "name": "那曲",
            "value": "290511"
        }, {
            "name": "阿里",
            "value": "17073"
        }, {
            "name": "林芝",
            "value": "5927894.8"
        }],
        "2012": [{
            "name": "西宁",
            "value": "165256.2"
        }, {
            "name": "海东",
            "value": "203715.6"
        }, {
            "name": "海北",
            "value": "522884"
        }, {
            "name": "海南",
            "value": "293276.4"
        }, {
            "name": "黄南",
            "value": "338256.2"
        }, {
            "name": "果洛",
            "value": "593485.6"
        }, {
            "name": "玉树",
            "value": "440440.6"
        }, {
            "name": "海西",
            "value": "327180.6"
        }, {
            "name": "拉萨",
            "value": "128679.2"
        }, {
            "name": "昌都",
            "value": "2818433.4"
        }, {
            "name": "山南",
            "value": "3005962.8"
        }, {
            "name": "日喀则",
            "value": "262498.4"
        }, {
            "name": "那曲",
            "value": "290511"
        }, {
            "name": "阿里",
            "value": "17073"
        }, {
            "name": "林芝",
            "value": "5927592.6"
        }],
        "2013": [{
            "name": "西宁",
            "value": "165230.8"
        }, {
            "name": "海东",
            "value": "203702.4"
        }, {
            "name": "海北",
            "value": "522502"
        }, {
            "name": "海南",
            "value": "293271.6"
        }, {
            "name": "黄南",
            "value": "338241.8"
        }, {
            "name": "果洛",
            "value": "593466.4"
        }, {
            "name": "玉树",
            "value": "440429.4"
        }, {
            "name": "海西",
            "value": "327121.4"
        }, {
            "name": "拉萨",
            "value": "128617.8"
        }, {
            "name": "昌都",
            "value": "2818426.6"
        }, {
            "name": "山南",
            "value": "3005874.2"
        }, {
            "name": "日喀则",
            "value": "262538.6"
        }, {
            "name": "那曲",
            "value": "290511"
        }, {
            "name": "阿里",
            "value": "17073"
        }, {
            "name": "林芝",
            "value": "5927290.4"
        }],
        "2014": [{
            "name": "西宁",
            "value": "165205.4"
        }, {
            "name": "海东",
            "value": "203689.2"
        }, {
            "name": "海北",
            "value": "522120"
        }, {
            "name": "海南",
            "value": "293266.8"
        }, {
            "name": "黄南",
            "value": "338227.4"
        }, {
            "name": "果洛",
            "value": "593447.2"
        }, {
            "name": "玉树",
            "value": "440418.2"
        }, {
            "name": "海西",
            "value": "327062.2"
        }, {
            "name": "拉萨",
            "value": "128556.4"
        }, {
            "name": "昌都",
            "value": "2818419.8"
        }, {
            "name": "山南",
            "value": "3005785.6"
        }, {
            "name": "日喀则",
            "value": "262578.8"
        }, {
            "name": "那曲",
            "value": "290511"
        }, {
            "name": "阿里",
            "value": "17073"
        }, {
            "name": "林芝",
            "value": "5926988.2"
        }],
        "2015": [{
            "name": "西宁",
            "value": "165180"
        }, {
            "name": "海东",
            "value": "203676"
        }, {
            "name": "海北",
            "value": "521738"
        }, {
            "name": "海南",
            "value": "293262"
        }, {
            "name": "黄南",
            "value": "338213"
        }, {
            "name": "果洛",
            "value": "593428"
        }, {
            "name": "玉树",
            "value": "440407"
        }, {
            "name": "海西",
            "value": "327003"
        }, {
            "name": "拉萨",
            "value": "128495"
        }, {
            "name": "昌都",
            "value": "2818413"
        }, {
            "name": "山南",
            "value": "3005697"
        }, {
            "name": "日喀则",
            "value": "262619"
        }, {
            "name": "那曲",
            "value": "290511"
        }, {
            "name": "阿里",
            "value": "17073"
        }, {
            "name": "林芝",
            "value": "5926686"
        }]
    },
    //拉萨
    {
	"2000": [{
		"name": "城关区",
		"value": "0 "
	}, {
		"name": "堆龙德庆区",
		"value": "0 "
	}, {
		"name": "达孜区",
		"value": "1844 "
	}, {
		"name": "林周县",
		"value": "12604 "
	}, {
		"name": "当雄县",
		"value": "41566 "
	}, {
		"name": "尼木县",
		"value": "3334 "
	}, {
		"name": "曲水县",
		"value": "2266 "
	}, {
		"name": "墨竹工卡县",
		"value": "7609 "
	}, {
		"name": "桑珠孜区",
		"value": "59608 "
	}, {
		"name": "江孜县",
		"value": "0 "
	}, {
		"name": "仁布县",
		"value": "1412 "
	}, {
		"name": "白朗县",
		"value": "1098 "
	}, {
		"name": "乃东区",
		"value": "2250 "
	}, {
		"name": "贡嘎县",
		"value": "17270 "
	}, {
		"name": "扎囊县",
		"value": "16705 "
	}, {
		"value": "7136 "
	}],
	"2001": [{
		"name": "城关区",
		"value": "0 "
	}, {
		"name": "堆龙德庆区",
		"value": "0 "
	}, {
		"name": "达孜区",
		"value": "1843 "
	}, {
		"name": "林周县",
		"value": "12604 "
	}, {
		"name": "当雄县",
		"value": "41566 "
	}, {
		"name": "尼木县",
		"value": "3334 "
	}, {
		"name": "曲水县",
		"value": "2266 "
	}, {
		"name": "墨竹工卡县",
		"value": "7606 "
	}, {
		"name": "桑珠孜区",
		"value": "59608 "
	}, {
		"name": "江孜县",
		"value": "0 "
	}, {
		"name": "仁布县",
		"value": "1412 "
	}, {
		"name": "白朗县",
		"value": "1098 "
	}, {
		"name": "乃东区",
		"value": "2250 "
	}, {
		"name": "贡嘎县",
		"value": "17270 "
	}, {
		"name": "扎囊县",
		"value": "16705 "
	}, {
		"value": "7134 "
	}],
	"2002": [{
		"name": "城关区",
		"value": "0 "
	}, {
		"name": "堆龙德庆区",
		"value": "0 "
	}, {
		"name": "达孜区",
		"value": "1842 "
	}, {
		"name": "林周县",
		"value": "12603 "
	}, {
		"name": "当雄县",
		"value": "41566 "
	}, {
		"name": "尼木县",
		"value": "3334 "
	}, {
		"name": "曲水县",
		"value": "2266 "
	}, {
		"name": "墨竹工卡县",
		"value": "7603 "
	}, {
		"name": "桑珠孜区",
		"value": "59608 "
	}, {
		"name": "江孜县",
		"value": "0 "
	}, {
		"name": "仁布县",
		"value": "1412 "
	}, {
		"name": "白朗县",
		"value": "1098 "
	}, {
		"name": "乃东区",
		"value": "2250 "
	}, {
		"name": "贡嘎县",
		"value": "17270 "
	}, {
		"name": "扎囊县",
		"value": "16705 "
	}, {
		"value": "7132 "
	}],
	"2003": [{
		"name": "城关区",
		"value": "0 "
	}, {
		"name": "堆龙德庆区",
		"value": "0 "
	}, {
		"name": "达孜区",
		"value": "1840 "
	}, {
		"name": "林周县",
		"value": "12603 "
	}, {
		"name": "当雄县",
		"value": "41566 "
	}, {
		"name": "尼木县",
		"value": "3334 "
	}, {
		"name": "曲水县",
		"value": "2266 "
	}, {
		"name": "墨竹工卡县",
		"value": "7599 "
	}, {
		"name": "桑珠孜区",
		"value": "59608 "
	}, {
		"name": "江孜县",
		"value": "0 "
	}, {
		"name": "仁布县",
		"value": "1412 "
	}, {
		"name": "白朗县",
		"value": "1098 "
	}, {
		"name": "乃东区",
		"value": "2250 "
	}, {
		"name": "贡嘎县",
		"value": "17269 "
	}, {
		"name": "扎囊县",
		"value": "16705 "
	}, {
		"value": "7131 "
	}],
	"2004": [{
		"name": "城关区",
		"value": "0 "
	}, {
		"name": "堆龙德庆区",
		"value": "0 "
	}, {
		"name": "达孜区",
		"value": "1839 "
	}, {
		"name": "林周县",
		"value": "12602 "
	}, {
		"name": "当雄县",
		"value": "41566 "
	}, {
		"name": "尼木县",
		"value": "3334 "
	}, {
		"name": "曲水县",
		"value": "2266 "
	}, {
		"name": "墨竹工卡县",
		"value": "7596 "
	}, {
		"name": "桑珠孜区",
		"value": "59608 "
	}, {
		"name": "江孜县",
		"value": "0 "
	}, {
		"name": "仁布县",
		"value": "1412 "
	}, {
		"name": "白朗县",
		"value": "1098 "
	}, {
		"name": "乃东区",
		"value": "2250 "
	}, {
		"name": "贡嘎县",
		"value": "17269 "
	}, {
		"name": "扎囊县",
		"value": "16705 "
	}, {
		"value": "7129 "
	}],
	"2005": [{
		"name": "城关区",
		"value": "0 "
	}, {
		"name": "堆龙德庆区",
		"value": "0 "
	}, {
		"name": "达孜区",
		"value": "1838 "
	}, {
		"name": "林周县",
		"value": "12602 "
	}, {
		"name": "当雄县",
		"value": "41566 "
	}, {
		"name": "尼木县",
		"value": "3334 "
	}, {
		"name": "曲水县",
		"value": "2266 "
	}, {
		"name": "墨竹工卡县",
		"value": "7593 "
	}, {
		"name": "桑珠孜区",
		"value": "59608 "
	}, {
		"name": "江孜县",
		"value": "0 "
	}, {
		"name": "仁布县",
		"value": "1412 "
	}, {
		"name": "白朗县",
		"value": "1098 "
	}, {
		"name": "乃东区",
		"value": "2250 "
	}, {
		"name": "贡嘎县",
		"value": "17269 "
	}, {
		"name": "扎囊县",
		"value": "16705 "
	}, {
		"value": "7127 "
	}],
	"2006": [{
		"name": "城关区",
		"value": "0 "
	}, {
		"name": "堆龙德庆区",
		"value": "0 "
	}, {
		"name": "达孜区",
		"value": "1837 "
	}, {
		"name": "林周县",
		"value": "12602 "
	}, {
		"name": "当雄县",
		"value": "41566 "
	}, {
		"name": "尼木县",
		"value": "3334 "
	}, {
		"name": "曲水县",
		"value": "2266 "
	}, {
		"name": "墨竹工卡县",
		"value": "7593 "
	}, {
		"name": "桑珠孜区",
		"value": "59608 "
	}, {
		"name": "江孜县",
		"value": "0 "
	}, {
		"name": "仁布县",
		"value": "1411 "
	}, {
		"name": "白朗县",
		"value": "1098 "
	}, {
		"name": "乃东区",
		"value": "2250 "
	}, {
		"name": "贡嘎县",
		"value": "17269 "
	}, {
		"name": "扎囊县",
		"value": "16705 "
	}, {
		"value": "7127 "
	}],
	"2007": [{
		"name": "城关区",
		"value": "0 "
	}, {
		"name": "堆龙德庆区",
		"value": "0 "
	}, {
		"name": "达孜区",
		"value": "1836 "
	}, {
		"name": "林周县",
		"value": "12602 "
	}, {
		"name": "当雄县",
		"value": "41566 "
	}, {
		"name": "尼木县",
		"value": "3334 "
	}, {
		"name": "曲水县",
		"value": "2266 "
	}, {
		"name": "墨竹工卡县",
		"value": "7593 "
	}, {
		"name": "桑珠孜区",
		"value": "59608 "
	}, {
		"name": "江孜县",
		"value": "0 "
	}, {
		"name": "仁布县",
		"value": "1410 "
	}, {
		"name": "白朗县",
		"value": "1098 "
	}, {
		"name": "乃东区",
		"value": "2250 "
	}, {
		"name": "贡嘎县",
		"value": "17269 "
	}, {
		"name": "扎囊县",
		"value": "16705 "
	}, {
		"value": "7127 "
	}],
	"2008": [{
		"name": "城关区",
		"value": "0 "
	}, {
		"name": "堆龙德庆区",
		"value": "0 "
	}, {
		"name": "达孜区",
		"value": "1835 "
	}, {
		"name": "林周县",
		"value": "12602 "
	}, {
		"name": "当雄县",
		"value": "41566 "
	}, {
		"name": "尼木县",
		"value": "3334 "
	}, {
		"name": "曲水县",
		"value": "2266 "
	}, {
		"name": "墨竹工卡县",
		"value": "7593 "
	}, {
		"name": "桑珠孜区",
		"value": "59608 "
	}, {
		"name": "江孜县",
		"value": "0 "
	}, {
		"name": "仁布县",
		"value": "1410 "
	}, {
		"name": "白朗县",
		"value": "1098 "
	}, {
		"name": "乃东区",
		"value": "2250 "
	}, {
		"name": "贡嘎县",
		"value": "17269 "
	}, {
		"name": "扎囊县",
		"value": "16705 "
	}, {
		"value": "7127 "
	}],
	"2009": [{
		"name": "城关区",
		"value": "0 "
	}, {
		"name": "堆龙德庆区",
		"value": "0 "
	}, {
		"name": "达孜区",
		"value": "1834 "
	}, {
		"name": "林周县",
		"value": "12602 "
	}, {
		"name": "当雄县",
		"value": "41566 "
	}, {
		"name": "尼木县",
		"value": "3334 "
	}, {
		"name": "曲水县",
		"value": "2266 "
	}, {
		"name": "墨竹工卡县",
		"value": "7593 "
	}, {
		"name": "桑珠孜区",
		"value": "59608 "
	}, {
		"name": "江孜县",
		"value": "0 "
	}, {
		"name": "仁布县",
		"value": "1409 "
	}, {
		"name": "白朗县",
		"value": "1098 "
	}, {
		"name": "乃东区",
		"value": "2250 "
	}, {
		"name": "贡嘎县",
		"value": "17269 "
	}, {
		"name": "扎囊县",
		"value": "16705 "
	}, {
		"value": "7127 "
	}],
	"2010": [{
		"name": "城关区",
		"value": "0 "
	}, {
		"name": "堆龙德庆区",
		"value": "0 "
	}, {
		"name": "达孜区",
		"value": "1833 "
	}, {
		"name": "林周县",
		"value": "12602 "
	}, {
		"name": "当雄县",
		"value": "41566 "
	}, {
		"name": "尼木县",
		"value": "3334 "
	}, {
		"name": "曲水县",
		"value": "2266 "
	}, {
		"name": "墨竹工卡县",
		"value": "7593 "
	}, {
		"name": "桑珠孜区",
		"value": "59608 "
	}, {
		"name": "江孜县",
		"value": "0 "
	}, {
		"name": "仁布县",
		"value": "1408 "
	}, {
		"name": "白朗县",
		"value": "1098 "
	}, {
		"name": "乃东区",
		"value": "2250 "
	}, {
		"name": "贡嘎县",
		"value": "17269 "
	}, {
		"name": "扎囊县",
		"value": "16705 "
	}, {
		"value": "7127 "
	}],
	"2011": [{
		"name": "城关区",
		"value": "0 "
	}, {
		"name": "堆龙德庆区",
		"value": "0 "
	}, {
		"name": "达孜区",
		"value": "1798 "
	}, {
		"name": "林周县",
		"value": "12602 "
	}, {
		"name": "当雄县",
		"value": "41550 "
	}, {
		"name": "尼木县",
		"value": "3334 "
	}, {
		"name": "曲水县",
		"value": "2266 "
	}, {
		"name": "墨竹工卡县",
		"value": "7588 "
	}, {
		"name": "桑珠孜区",
		"value": "59602 "
	}, {
		"name": "江孜县",
		"value": "0 "
	}, {
		"name": "仁布县",
		"value": "1407 "
	}, {
		"name": "白朗县",
		"value": "1098 "
	}, {
		"name": "乃东区",
		"value": "2250 "
	}, {
		"name": "贡嘎县",
		"value": "17267 "
	}, {
		"name": "扎囊县",
		"value": "16692 "
	}, {
		"value": "7127 "
	}],
	"2012": [{
		"name": "城关区",
		"value": "0 "
	}, {
		"name": "堆龙德庆区",
		"value": "0 "
	}, {
		"name": "达孜区",
		"value": "1764 "
	}, {
		"name": "林周县",
		"value": "12602 "
	}, {
		"name": "当雄县",
		"value": "41534 "
	}, {
		"name": "尼木县",
		"value": "3334 "
	}, {
		"name": "曲水县",
		"value": "2266 "
	}, {
		"name": "墨竹工卡县",
		"value": "7583 "
	}, {
		"name": "桑珠孜区",
		"value": "59596 "
	}, {
		"name": "江孜县",
		"value": "0 "
	}, {
		"name": "仁布县",
		"value": "1406 "
	}, {
		"name": "白朗县",
		"value": "1098 "
	}, {
		"name": "乃东区",
		"value": "2250 "
	}, {
		"name": "贡嘎县",
		"value": "17264 "
	}, {
		"name": "扎囊县",
		"value": "16679 "
	}, {
		"value": "7127 "
	}],
	"2013": [{
		"name": "城关区",
		"value": "0 "
	}, {
		"name": "堆龙德庆区",
		"value": "0 "
	}, {
		"name": "达孜区",
		"value": "1729 "
	}, {
		"name": "林周县",
		"value": "12602 "
	}, {
		"name": "当雄县",
		"value": "41518 "
	}, {
		"name": "尼木县",
		"value": "3334 "
	}, {
		"name": "曲水县",
		"value": "2266 "
	}, {
		"name": "墨竹工卡县",
		"value": "7579 "
	}, {
		"name": "桑珠孜区",
		"value": "59590 "
	}, {
		"name": "江孜县",
		"value": "0 "
	}, {
		"name": "仁布县",
		"value": "1406 "
	}, {
		"name": "白朗县",
		"value": "1098 "
	}, {
		"name": "乃东区",
		"value": "2250 "
	}, {
		"name": "贡嘎县",
		"value": "17262 "
	}, {
		"name": "扎囊县",
		"value": "16666 "
	}, {
		"value": "7127 "
	}],
	"2014": [{
		"name": "城关区",
		"value": "0 "
	}, {
		"name": "堆龙德庆区",
		"value": "0 "
	}, {
		"name": "达孜区",
		"value": "1695 "
	}, {
		"name": "林周县",
		"value": "12602 "
	}, {
		"name": "当雄县",
		"value": "41502 "
	}, {
		"name": "尼木县",
		"value": "3334 "
	}, {
		"name": "曲水县",
		"value": "2266 "
	}, {
		"name": "墨竹工卡县",
		"value": "7574 "
	}, {
		"name": "桑珠孜区",
		"value": "59584 "
	}, {
		"name": "江孜县",
		"value": "0 "
	}, {
		"name": "仁布县",
		"value": "1405 "
	}, {
		"name": "白朗县",
		"value": "1098 "
	}, {
		"name": "乃东区",
		"value": "2250 "
	}, {
		"name": "贡嘎县",
		"value": "17259 "
	}, {
		"name": "扎囊县",
		"value": "16653 "
	}, {
		"value": "7127 "
	}],
	"2015": [{
		"name": "城关区",
		"value": "0 "
	}, {
		"name": "堆龙德庆区",
		"value": "0 "
	}, {
		"name": "达孜区",
		"value": "1660 "
	}, {
		"name": "林周县",
		"value": "12602 "
	}, {
		"name": "当雄县",
		"value": "41486 "
	}, {
		"name": "尼木县",
		"value": "3334 "
	}, {
		"name": "曲水县",
		"value": "2266 "
	}, {
		"name": "墨竹工卡县",
		"value": "7569 "
	}, {
		"name": "桑珠孜区",
		"value": "59578 "
	}, {
		"name": "江孜县",
		"value": "0 "
	}, {
		"name": "仁布县",
		"value": "1404 "
	}, {
		"name": "白朗县",
		"value": "1098 "
	}, {
		"name": "乃东区",
		"value": "2250 "
	}, {
		"name": "贡嘎县",
		"value": "17257 "
	}, {
		"name": "扎囊县",
		"value": "16640 "
	}, {
		"value": "7127 "
	}]
    },
    //兰西
    {
        "2000": [{
            "name": "永登县",
            "value": 0
        }, {
            "name": "皋兰县",
            "value": 0
        }, {
            "name": "榆中县",
            "value": 0
        }, {
            "name": "靖远县",
            "value": 0
        }, {
            "name": "景泰县",
            "value": 0
        }, {
            "name": "安定区",
            "value": 0
        }, {
            "name": "陇西县",
            "value": 0
        }, {
            "name": "渭源县",
            "value": 0
        }, {
            "name": "临洮县",
            "value": 0
        }, {
            "name": "临夏市",
            "value": 0
        }, {
            "name": "永靖县",
            "value": 0
        }, {
            "name": "东乡县",
            "value": 0
        }, {
            "name": "积石山县",
            "value": 0
        }, {
            "name": "大通县",
            "value": 0
        }, {
            "name": "湟中县",
            "value": 0
        }, {
            "name": "湟源县",
            "value": 0
        }, {
            "name": "平安县",
            "value": 0
        }, {
            "name": "民和县",
            "value": 0
        }, {
            "name": "乐都县",
            "value": 0
        }, {
            "name": "互助县",
            "value": 0
        }, {
            "name": "化隆县",
            "value": 0
        }, {
            "name": "循化县",
            "value": 0
        }, {
            "name": "海晏县",
            "value": 0
        }, {
            "name": "共和县",
            "value": 0
        }, {
            "name": "贵德县",
            "value": 0
        }, {
            "name": "贵南县",
            "value": 0
        }, {
            "name": "同仁县",
            "value": 0
        }, {
            "name": "尖扎县",
            "value": 0
        }],
        "2001": [{
            "name": "永登县",
            "value": 0
        }, {
            "name": "皋兰县",
            "value": 0
        }, {
            "name": "榆中县",
            "value": 0
        }, {
            "name": "靖远县",
            "value": 0
        }, {
            "name": "景泰县",
            "value": 0
        }, {
            "name": "安定区",
            "value": 0
        }, {
            "name": "陇西县",
            "value": 0
        }, {
            "name": "渭源县",
            "value": 0
        }, {
            "name": "临洮县",
            "value": 0
        }, {
            "name": "临夏市",
            "value": 0
        }, {
            "name": "永靖县",
            "value": 0
        }, {
            "name": "东乡县",
            "value": 0
        }, {
            "name": "积石山县",
            "value": 0
        }, {
            "name": "大通县",
            "value": 0
        }, {
            "name": "湟中县",
            "value": 0
        }, {
            "name": "湟源县",
            "value": 0
        }, {
            "name": "平安县",
            "value": 0
        }, {
            "name": "民和县",
            "value": 0
        }, {
            "name": "乐都县",
            "value": 0
        }, {
            "name": "互助县",
            "value": 0
        }, {
            "name": "化隆县",
            "value": 0
        }, {
            "name": "循化县",
            "value": 0
        }, {
            "name": "海晏县",
            "value": 0
        }, {
            "name": "共和县",
            "value": 0
        }, {
            "name": "贵德县",
            "value": 0
        }, {
            "name": "贵南县",
            "value": 0
        }, {
            "name": "同仁县",
            "value": 0
        }, {
            "name": "尖扎县",
            "value": 0
        }],
        "2002": [{
            "name": "永登县",
            "value": 0
        }, {
            "name": "皋兰县",
            "value": 0
        }, {
            "name": "榆中县",
            "value": 0
        }, {
            "name": "靖远县",
            "value": 0
        }, {
            "name": "景泰县",
            "value": 0
        }, {
            "name": "安定区",
            "value": 0
        }, {
            "name": "陇西县",
            "value": 0
        }, {
            "name": "渭源县",
            "value": 0
        }, {
            "name": "临洮县",
            "value": 0
        }, {
            "name": "临夏市",
            "value": 0
        }, {
            "name": "永靖县",
            "value": 0
        }, {
            "name": "东乡县",
            "value": 0
        }, {
            "name": "积石山县",
            "value": 0
        }, {
            "name": "大通县",
            "value": 0
        }, {
            "name": "湟中县",
            "value": 0
        }, {
            "name": "湟源县",
            "value": 0
        }, {
            "name": "平安县",
            "value": 0
        }, {
            "name": "民和县",
            "value": 0
        }, {
            "name": "乐都县",
            "value": 0
        }, {
            "name": "互助县",
            "value": 0
        }, {
            "name": "化隆县",
            "value": 0
        }, {
            "name": "循化县",
            "value": 0
        }, {
            "name": "海晏县",
            "value": 0
        }, {
            "name": "共和县",
            "value": 0
        }, {
            "name": "贵德县",
            "value": 0
        }, {
            "name": "贵南县",
            "value": 0
        }, {
            "name": "同仁县",
            "value": 0
        }, {
            "name": "尖扎县",
            "value": 0
        }],
        "2003": [{
            "name": "永登县",
            "value": 0
        }, {
            "name": "皋兰县",
            "value": 0
        }, {
            "name": "榆中县",
            "value": 0
        }, {
            "name": "靖远县",
            "value": 0
        }, {
            "name": "景泰县",
            "value": 0
        }, {
            "name": "安定区",
            "value": 0
        }, {
            "name": "陇西县",
            "value": 0
        }, {
            "name": "渭源县",
            "value": 0
        }, {
            "name": "临洮县",
            "value": 0
        }, {
            "name": "临夏市",
            "value": 0
        }, {
            "name": "永靖县",
            "value": 0
        }, {
            "name": "东乡县",
            "value": 0
        }, {
            "name": "积石山县",
            "value": 0
        }, {
            "name": "大通县",
            "value": 0
        }, {
            "name": "湟中县",
            "value": 0
        }, {
            "name": "湟源县",
            "value": 0
        }, {
            "name": "平安县",
            "value": 0
        }, {
            "name": "民和县",
            "value": 0
        }, {
            "name": "乐都县",
            "value": 0
        }, {
            "name": "互助县",
            "value": 0
        }, {
            "name": "化隆县",
            "value": 0
        }, {
            "name": "循化县",
            "value": 0
        }, {
            "name": "海晏县",
            "value": 0
        }, {
            "name": "共和县",
            "value": 0
        }, {
            "name": "贵德县",
            "value": 0
        }, {
            "name": "贵南县",
            "value": 0
        }, {
            "name": "同仁县",
            "value": 0
        }, {
            "name": "尖扎县",
            "value": 0
        }],
        "2004": [{
            "name": "永登县",
            "value": 0
        }, {
            "name": "皋兰县",
            "value": 0
        }, {
            "name": "榆中县",
            "value": 0
        }, {
            "name": "靖远县",
            "value": 0
        }, {
            "name": "景泰县",
            "value": 0
        }, {
            "name": "安定区",
            "value": 0
        }, {
            "name": "陇西县",
            "value": 0
        }, {
            "name": "渭源县",
            "value": 0
        }, {
            "name": "临洮县",
            "value": 0
        }, {
            "name": "临夏市",
            "value": 0
        }, {
            "name": "永靖县",
            "value": 0
        }, {
            "name": "东乡县",
            "value": 0
        }, {
            "name": "积石山县",
            "value": 0
        }, {
            "name": "大通县",
            "value": 0
        }, {
            "name": "湟中县",
            "value": 0
        }, {
            "name": "湟源县",
            "value": 0
        }, {
            "name": "平安县",
            "value": 0
        }, {
            "name": "民和县",
            "value": 0
        }, {
            "name": "乐都县",
            "value": 0
        }, {
            "name": "互助县",
            "value": 0
        }, {
            "name": "化隆县",
            "value": 0
        }, {
            "name": "循化县",
            "value": 0
        }, {
            "name": "海晏县",
            "value": 0
        }, {
            "name": "共和县",
            "value": 0
        }, {
            "name": "贵德县",
            "value": 0
        }, {
            "name": "贵南县",
            "value": 0
        }, {
            "name": "同仁县",
            "value": 0
        }, {
            "name": "尖扎县",
            "value": 0
        }],
        "2005": [{
            "name": "永登县",
            "value": 0
        }, {
            "name": "皋兰县",
            "value": 0
        }, {
            "name": "榆中县",
            "value": 0
        }, {
            "name": "靖远县",
            "value": 0
        }, {
            "name": "景泰县",
            "value": 0
        }, {
            "name": "安定区",
            "value": 0
        }, {
            "name": "陇西县",
            "value": 0
        }, {
            "name": "渭源县",
            "value": 0
        }, {
            "name": "临洮县",
            "value": 0
        }, {
            "name": "临夏市",
            "value": 0
        }, {
            "name": "永靖县",
            "value": 0
        }, {
            "name": "东乡县",
            "value": 0
        }, {
            "name": "积石山县",
            "value": 0
        }, {
            "name": "大通县",
            "value": 0
        }, {
            "name": "湟中县",
            "value": 0
        }, {
            "name": "湟源县",
            "value": 0
        }, {
            "name": "平安县",
            "value": 0
        }, {
            "name": "民和县",
            "value": 0
        }, {
            "name": "乐都县",
            "value": 0
        }, {
            "name": "互助县",
            "value": 0
        }, {
            "name": "化隆县",
            "value": 0
        }, {
            "name": "循化县",
            "value": 0
        }, {
            "name": "海晏县",
            "value": 0
        }, {
            "name": "共和县",
            "value": 0
        }, {
            "name": "贵德县",
            "value": 0
        }, {
            "name": "贵南县",
            "value": 0
        }, {
            "name": "同仁县",
            "value": 0
        }, {
            "name": "尖扎县",
            "value": 0
        }],
        "2006": [{
            "name": "永登县",
            "value": 0
        }, {
            "name": "皋兰县",
            "value": 0
        }, {
            "name": "榆中县",
            "value": 0
        }, {
            "name": "靖远县",
            "value": 0
        }, {
            "name": "景泰县",
            "value": 0
        }, {
            "name": "安定区",
            "value": 0
        }, {
            "name": "陇西县",
            "value": 0
        }, {
            "name": "渭源县",
            "value": 0
        }, {
            "name": "临洮县",
            "value": 0
        }, {
            "name": "临夏市",
            "value": 0
        }, {
            "name": "永靖县",
            "value": 0
        }, {
            "name": "东乡县",
            "value": 0
        }, {
            "name": "积石山县",
            "value": 0
        }, {
            "name": "大通县",
            "value": 0
        }, {
            "name": "湟中县",
            "value": 0
        }, {
            "name": "湟源县",
            "value": 0
        }, {
            "name": "平安县",
            "value": 0
        }, {
            "name": "民和县",
            "value": 0
        }, {
            "name": "乐都县",
            "value": 0
        }, {
            "name": "互助县",
            "value": 0
        }, {
            "name": "化隆县",
            "value": 0
        }, {
            "name": "循化县",
            "value": 0
        }, {
            "name": "海晏县",
            "value": 0
        }, {
            "name": "共和县",
            "value": 0
        }, {
            "name": "贵德县",
            "value": 0
        }, {
            "name": "贵南县",
            "value": 0
        }, {
            "name": "同仁县",
            "value": 0
        }, {
            "name": "尖扎县",
            "value": 0
        }],
        "2007": [{
            "name": "永登县",
            "value": 0
        }, {
            "name": "皋兰县",
            "value": 0
        }, {
            "name": "榆中县",
            "value": 0
        }, {
            "name": "靖远县",
            "value": 0
        }, {
            "name": "景泰县",
            "value": 0
        }, {
            "name": "安定区",
            "value": 0
        }, {
            "name": "陇西县",
            "value": 0
        }, {
            "name": "渭源县",
            "value": 0
        }, {
            "name": "临洮县",
            "value": 0
        }, {
            "name": "临夏市",
            "value": 0
        }, {
            "name": "永靖县",
            "value": 0
        }, {
            "name": "东乡县",
            "value": 0
        }, {
            "name": "积石山县",
            "value": 0
        }, {
            "name": "大通县",
            "value": 0
        }, {
            "name": "湟中县",
            "value": 0
        }, {
            "name": "湟源县",
            "value": 0
        }, {
            "name": "平安县",
            "value": 0
        }, {
            "name": "民和县",
            "value": 0
        }, {
            "name": "乐都县",
            "value": 0
        }, {
            "name": "互助县",
            "value": 0
        }, {
            "name": "化隆县",
            "value": 0
        }, {
            "name": "循化县",
            "value": 0
        }, {
            "name": "海晏县",
            "value": 0
        }, {
            "name": "共和县",
            "value": 0
        }, {
            "name": "贵德县",
            "value": 0
        }, {
            "name": "贵南县",
            "value": 0
        }, {
            "name": "同仁县",
            "value": 0
        }, {
            "name": "尖扎县",
            "value": 0
        }],
        "2008": [{
            "name": "永登县",
            "value": 0
        }, {
            "name": "皋兰县",
            "value": 0
        }, {
            "name": "榆中县",
            "value": 0
        }, {
            "name": "靖远县",
            "value": 0
        }, {
            "name": "景泰县",
            "value": 0
        }, {
            "name": "安定区",
            "value": 0
        }, {
            "name": "陇西县",
            "value": 0
        }, {
            "name": "渭源县",
            "value": 0
        }, {
            "name": "临洮县",
            "value": 0
        }, {
            "name": "临夏市",
            "value": 0
        }, {
            "name": "永靖县",
            "value": 0
        }, {
            "name": "东乡县",
            "value": 0
        }, {
            "name": "积石山县",
            "value": 0
        }, {
            "name": "大通县",
            "value": 0
        }, {
            "name": "湟中县",
            "value": 0
        }, {
            "name": "湟源县",
            "value": 0
        }, {
            "name": "平安县",
            "value": 0
        }, {
            "name": "民和县",
            "value": 0
        }, {
            "name": "乐都县",
            "value": 0
        }, {
            "name": "互助县",
            "value": 0
        }, {
            "name": "化隆县",
            "value": 0
        }, {
            "name": "循化县",
            "value": 0
        }, {
            "name": "海晏县",
            "value": 0
        }, {
            "name": "共和县",
            "value": 0
        }, {
            "name": "贵德县",
            "value": 0
        }, {
            "name": "贵南县",
            "value": 0
        }, {
            "name": "同仁县",
            "value": 0
        }, {
            "name": "尖扎县",
            "value": 0
        }],
        "2009": [{
            "name": "永登县",
            "value": 0
        }, {
            "name": "皋兰县",
            "value": 0
        }, {
            "name": "榆中县",
            "value": 0
        }, {
            "name": "靖远县",
            "value": 0
        }, {
            "name": "景泰县",
            "value": 0
        }, {
            "name": "安定区",
            "value": 0
        }, {
            "name": "陇西县",
            "value": 0
        }, {
            "name": "渭源县",
            "value": 0
        }, {
            "name": "临洮县",
            "value": 0
        }, {
            "name": "临夏市",
            "value": 0
        }, {
            "name": "永靖县",
            "value": 0
        }, {
            "name": "东乡县",
            "value": 0
        }, {
            "name": "积石山县",
            "value": 0
        }, {
            "name": "大通县",
            "value": 0
        }, {
            "name": "湟中县",
            "value": 0
        }, {
            "name": "湟源县",
            "value": 0
        }, {
            "name": "平安县",
            "value": 0
        }, {
            "name": "民和县",
            "value": 0
        }, {
            "name": "乐都县",
            "value": 0
        }, {
            "name": "互助县",
            "value": 0
        }, {
            "name": "化隆县",
            "value": 0
        }, {
            "name": "循化县",
            "value": 0
        }, {
            "name": "海晏县",
            "value": 0
        }, {
            "name": "共和县",
            "value": 0
        }, {
            "name": "贵德县",
            "value": 0
        }, {
            "name": "贵南县",
            "value": 0
        }, {
            "name": "同仁县",
            "value": 0
        }, {
            "name": "尖扎县",
            "value": 0
        }],
        "2010": [{
            "name": "永登县",
            "value": 0
        }, {
            "name": "皋兰县",
            "value": 0
        }, {
            "name": "榆中县",
            "value": 0
        }, {
            "name": "靖远县",
            "value": 0
        }, {
            "name": "景泰县",
            "value": 0
        }, {
            "name": "安定区",
            "value": 0
        }, {
            "name": "陇西县",
            "value": 0
        }, {
            "name": "渭源县",
            "value": 0
        }, {
            "name": "临洮县",
            "value": 0
        }, {
            "name": "临夏市",
            "value": 0
        }, {
            "name": "永靖县",
            "value": 0
        }, {
            "name": "东乡县",
            "value": 0
        }, {
            "name": "积石山县",
            "value": 0
        }, {
            "name": "大通县",
            "value": 0
        }, {
            "name": "湟中县",
            "value": 0
        }, {
            "name": "湟源县",
            "value": 0
        }, {
            "name": "平安县",
            "value": 0
        }, {
            "name": "民和县",
            "value": 0
        }, {
            "name": "乐都县",
            "value": 0
        }, {
            "name": "互助县",
            "value": 0
        }, {
            "name": "化隆县",
            "value": 0
        }, {
            "name": "循化县",
            "value": 0
        }, {
            "name": "海晏县",
            "value": 0
        }, {
            "name": "共和县",
            "value": 0
        }, {
            "name": "贵德县",
            "value": 0
        }, {
            "name": "贵南县",
            "value": 0
        }, {
            "name": "同仁县",
            "value": 0
        }, {
            "name": "尖扎县",
            "value": 0
        }],
        "2011": [{
            "name": "永登县",
            "value": 0
        }, {
            "name": "皋兰县",
            "value": 0
        }, {
            "name": "榆中县",
            "value": 0
        }, {
            "name": "靖远县",
            "value": 0
        }, {
            "name": "景泰县",
            "value": 0
        }, {
            "name": "安定区",
            "value": 0
        }, {
            "name": "陇西县",
            "value": 0
        }, {
            "name": "渭源县",
            "value": 0
        }, {
            "name": "临洮县",
            "value": 0
        }, {
            "name": "临夏市",
            "value": 0
        }, {
            "name": "永靖县",
            "value": 0
        }, {
            "name": "东乡县",
            "value": 0
        }, {
            "name": "积石山县",
            "value": 0
        }, {
            "name": "大通县",
            "value": 0
        }, {
            "name": "湟中县",
            "value": 0
        }, {
            "name": "湟源县",
            "value": 0
        }, {
            "name": "平安县",
            "value": 0
        }, {
            "name": "民和县",
            "value": 0
        }, {
            "name": "乐都县",
            "value": 0
        }, {
            "name": "互助县",
            "value": 0
        }, {
            "name": "化隆县",
            "value": 0
        }, {
            "name": "循化县",
            "value": 0
        }, {
            "name": "海晏县",
            "value": 0
        }, {
            "name": "共和县",
            "value": 0
        }, {
            "name": "贵德县",
            "value": 0
        }, {
            "name": "贵南县",
            "value": 0
        }, {
            "name": "同仁县",
            "value": 0
        }, {
            "name": "尖扎县",
            "value": 0
        }],
        "2012": [{
            "name": "永登县",
            "value": 0
        }, {
            "name": "皋兰县",
            "value": 0
        }, {
            "name": "榆中县",
            "value": 0
        }, {
            "name": "靖远县",
            "value": 0
        }, {
            "name": "景泰县",
            "value": 0
        }, {
            "name": "安定区",
            "value": 0
        }, {
            "name": "陇西县",
            "value": 0
        }, {
            "name": "渭源县",
            "value": 0
        }, {
            "name": "临洮县",
            "value": 0
        }, {
            "name": "临夏市",
            "value": 0
        }, {
            "name": "永靖县",
            "value": 0
        }, {
            "name": "东乡县",
            "value": 0
        }, {
            "name": "积石山县",
            "value": 0
        }, {
            "name": "大通县",
            "value": 0
        }, {
            "name": "湟中县",
            "value": 0
        }, {
            "name": "湟源县",
            "value": 0
        }, {
            "name": "平安县",
            "value": 0
        }, {
            "name": "民和县",
            "value": 0
        }, {
            "name": "乐都县",
            "value": 0
        }, {
            "name": "互助县",
            "value": 0
        }, {
            "name": "化隆县",
            "value": 0
        }, {
            "name": "循化县",
            "value": 0
        }, {
            "name": "海晏县",
            "value": 0
        }, {
            "name": "共和县",
            "value": 0
        }, {
            "name": "贵德县",
            "value": 0
        }, {
            "name": "贵南县",
            "value": 0
        }, {
            "name": "同仁县",
            "value": 0
        }, {
            "name": "尖扎县",
            "value": 0
        }],
        "2013": [{
            "name": "永登县",
            "value": 0
        }, {
            "name": "皋兰县",
            "value": 0
        }, {
            "name": "榆中县",
            "value": 0
        }, {
            "name": "靖远县",
            "value": 0
        }, {
            "name": "景泰县",
            "value": 0
        }, {
            "name": "安定区",
            "value": 0
        }, {
            "name": "陇西县",
            "value": 0
        }, {
            "name": "渭源县",
            "value": 0
        }, {
            "name": "临洮县",
            "value": 0
        }, {
            "name": "临夏市",
            "value": 0
        }, {
            "name": "永靖县",
            "value": 0
        }, {
            "name": "东乡县",
            "value": 0
        }, {
            "name": "积石山县",
            "value": 0
        }, {
            "name": "大通县",
            "value": 0
        }, {
            "name": "湟中县",
            "value": 0
        }, {
            "name": "湟源县",
            "value": 0
        }, {
            "name": "平安县",
            "value": 0
        }, {
            "name": "民和县",
            "value": 0
        }, {
            "name": "乐都县",
            "value": 0
        }, {
            "name": "互助县",
            "value": 0
        }, {
            "name": "化隆县",
            "value": 0
        }, {
            "name": "循化县",
            "value": 0
        }, {
            "name": "海晏县",
            "value": 0
        }, {
            "name": "共和县",
            "value": 0
        }, {
            "name": "贵德县",
            "value": 0
        }, {
            "name": "贵南县",
            "value": 0
        }, {
            "name": "同仁县",
            "value": 0
        }, {
            "name": "尖扎县",
            "value": 0
        }],
        "2014": [{
            "name": "永登县",
            "value": 0
        }, {
            "name": "皋兰县",
            "value": 0
        }, {
            "name": "榆中县",
            "value": 0
        }, {
            "name": "靖远县",
            "value": 0
        }, {
            "name": "景泰县",
            "value": 0
        }, {
            "name": "安定区",
            "value": 0
        }, {
            "name": "陇西县",
            "value": 0
        }, {
            "name": "渭源县",
            "value": 0
        }, {
            "name": "临洮县",
            "value": 0
        }, {
            "name": "临夏市",
            "value": 0
        }, {
            "name": "永靖县",
            "value": 0
        }, {
            "name": "东乡县",
            "value": 0
        }, {
            "name": "积石山县",
            "value": 0
        }, {
            "name": "大通县",
            "value": 0
        }, {
            "name": "湟中县",
            "value": 0
        }, {
            "name": "湟源县",
            "value": 0
        }, {
            "name": "平安县",
            "value": 0
        }, {
            "name": "民和县",
            "value": 0
        }, {
            "name": "乐都县",
            "value": 0
        }, {
            "name": "互助县",
            "value": 0
        }, {
            "name": "化隆县",
            "value": 0
        }, {
            "name": "循化县",
            "value": 0
        }, {
            "name": "海晏县",
            "value": 0
        }, {
            "name": "共和县",
            "value": 0
        }, {
            "name": "贵德县",
            "value": 0
        }, {
            "name": "贵南县",
            "value": 0
        }, {
            "name": "同仁县",
            "value": 0
        }, {
            "name": "尖扎县",
            "value": 0
        }],
        "2015": [{
            "name": "永登县",
            "value": 0
        }, {
            "name": "皋兰县",
            "value": 0
        }, {
            "name": "榆中县",
            "value": 0
        }, {
            "name": "靖远县",
            "value": 0
        }, {
            "name": "景泰县",
            "value": 0
        }, {
            "name": "安定区",
            "value": 0
        }, {
            "name": "陇西县",
            "value": 0
        }, {
            "name": "渭源县",
            "value": 0
        }, {
            "name": "临洮县",
            "value": 0
        }, {
            "name": "临夏市",
            "value": 0
        }, {
            "name": "永靖县",
            "value": 0
        }, {
            "name": "东乡县",
            "value": 0
        }, {
            "name": "积石山县",
            "value": 0
        }, {
            "name": "大通县",
            "value": 0
        }, {
            "name": "湟中县",
            "value": 0
        }, {
            "name": "湟源县",
            "value": 0
        }, {
            "name": "平安县",
            "value": 0
        }, {
            "name": "民和县",
            "value": 0
        }, {
            "name": "乐都县",
            "value": 0
        }, {
            "name": "互助县",
            "value": 0
        }, {
            "name": "化隆县",
            "value": 0
        }, {
            "name": "循化县",
            "value": 0
        }, {
            "name": "海晏县",
            "value": 0
        }, {
            "name": "共和县",
            "value": 0
        }, {
            "name": "贵德县",
            "value": 0
        }, {
            "name": "贵南县",
            "value": 0
        }, {
            "name": "同仁县",
            "value": 0
        }, {
            "name": "尖扎县",
            "value": 0
        }]
    },
    //边境
    {
        "2000": [{
            "name": "定日县",
            "value": "44611"
        }, {
            "name": "康马县",
            "value": "901"
        }, {
            "name": "定结县",
            "value": "26411"
        }, {
            "name": "仲巴县",
            "value": "3123"
        }, {
            "name": "亚东县",
            "value": "89821"
        }, {
            "name": "吉隆县",
            "value": "58913"
        }, {
            "name": "聂拉木县",
            "value": "26447"
        }, {
            "name": "萨嘎县",
            "value": "0"
        }, {
            "name": "岗巴县",
            "value": "0"
        }, {
            "name": "普兰县",
            "value": "2729"
        }, {
            "name": "札达县",
            "value": "0"
        }, {
            "name": "噶尔县",
            "value": "0"
        }, {
            "name": "日土县",
            "value": "0"
        }, {
            "name": "米林县",
            "value": "320442"
        }, {
            "name": "墨脱县",
            "value": "2460382"
        }, {
            "name": "察隅县",
            "value": "1885803"
        }, {
            "name": "朗县",
            "value": "123340"
        }, {
            "name": "洛扎县",
            "value": "94863"
        }, {
            "name": "隆子县",
            "value": "298916"
        }, {
            "name": "错那县",
            "value": "2411053"
        }, {
            "name": "浪卡子县",
            "value": "0"
        }],
        "2001": [{
            "name": "定日县",
            "value": "44611"
        }, {
            "name": "康马县",
            "value": "901"
        }, {
            "name": "定结县",
            "value": "26411"
        }, {
            "name": "仲巴县",
            "value": "3123"
        }, {
            "name": "亚东县",
            "value": "89821"
        }, {
            "name": "吉隆县",
            "value": "58913"
        }, {
            "name": "聂拉木县",
            "value": "26447"
        }, {
            "name": "萨嘎县",
            "value": "0"
        }, {
            "name": "岗巴县",
            "value": "0"
        }, {
            "name": "普兰县",
            "value": "2729"
        }, {
            "name": "札达县",
            "value": "0"
        }, {
            "name": "噶尔县",
            "value": "0"
        }, {
            "name": "日土县",
            "value": "0"
        }, {
            "name": "米林县",
            "value": "320442"
        }, {
            "name": "墨脱县",
            "value": "2460453"
        }, {
            "name": "察隅县",
            "value": "1885803"
        }, {
            "name": "朗县",
            "value": "123340"
        }, {
            "name": "洛扎县",
            "value": "94863"
        }, {
            "name": "隆子县",
            "value": "298916"
        }, {
            "name": "错那县",
            "value": "2411053"
        }, {
            "name": "浪卡子县",
            "value": "0"
        }],
        "2002": [{
            "name": "定日县",
            "value": "44611"
        }, {
            "name": "康马县",
            "value": "901"
        }, {
            "name": "定结县",
            "value": "26411"
        }, {
            "name": "仲巴县",
            "value": "3123"
        }, {
            "name": "亚东县",
            "value": "89821"
        }, {
            "name": "吉隆县",
            "value": "58913"
        }, {
            "name": "聂拉木县",
            "value": "26447"
        }, {
            "name": "萨嘎县",
            "value": "0"
        }, {
            "name": "岗巴县",
            "value": "0"
        }, {
            "name": "普兰县",
            "value": "2729"
        }, {
            "name": "札达县",
            "value": "0"
        }, {
            "name": "噶尔县",
            "value": "0"
        }, {
            "name": "日土县",
            "value": "0"
        }, {
            "name": "米林县",
            "value": "320442"
        }, {
            "name": "墨脱县",
            "value": "2460524"
        }, {
            "name": "察隅县",
            "value": "1885803"
        }, {
            "name": "朗县",
            "value": "123340"
        }, {
            "name": "洛扎县",
            "value": "94863"
        }, {
            "name": "隆子县",
            "value": "298916"
        }, {
            "name": "错那县",
            "value": "2411053"
        }, {
            "name": "浪卡子县",
            "value": "0"
        }],
        "2003": [{
            "name": "定日县",
            "value": "44611"
        }, {
            "name": "康马县",
            "value": "901"
        }, {
            "name": "定结县",
            "value": "26411"
        }, {
            "name": "仲巴县",
            "value": "3123"
        }, {
            "name": "亚东县",
            "value": "89821"
        }, {
            "name": "吉隆县",
            "value": "58913"
        }, {
            "name": "聂拉木县",
            "value": "26447"
        }, {
            "name": "萨嘎县",
            "value": "0"
        }, {
            "name": "岗巴县",
            "value": "0"
        }, {
            "name": "普兰县",
            "value": "2729"
        }, {
            "name": "札达县",
            "value": "0"
        }, {
            "name": "噶尔县",
            "value": "0"
        }, {
            "name": "日土县",
            "value": "0"
        }, {
            "name": "米林县",
            "value": "320442"
        }, {
            "name": "墨脱县",
            "value": "2460594"
        }, {
            "name": "察隅县",
            "value": "1885803"
        }, {
            "name": "朗县",
            "value": "123340"
        }, {
            "name": "洛扎县",
            "value": "94863"
        }, {
            "name": "隆子县",
            "value": "298916"
        }, {
            "name": "错那县",
            "value": "2411053"
        }, {
            "name": "浪卡子县",
            "value": "0"
        }],
        "2004": [{
            "name": "定日县",
            "value": "44611"
        }, {
            "name": "康马县",
            "value": "901"
        }, {
            "name": "定结县",
            "value": "26411"
        }, {
            "name": "仲巴县",
            "value": "3123"
        }, {
            "name": "亚东县",
            "value": "89821"
        }, {
            "name": "吉隆县",
            "value": "58913"
        }, {
            "name": "聂拉木县",
            "value": "26447"
        }, {
            "name": "萨嘎县",
            "value": "0"
        }, {
            "name": "岗巴县",
            "value": "0"
        }, {
            "name": "普兰县",
            "value": "2729"
        }, {
            "name": "札达县",
            "value": "0"
        }, {
            "name": "噶尔县",
            "value": "0"
        }, {
            "name": "日土县",
            "value": "0"
        }, {
            "name": "米林县",
            "value": "320442"
        }, {
            "name": "墨脱县",
            "value": "2460665"
        }, {
            "name": "察隅县",
            "value": "1885803"
        }, {
            "name": "朗县",
            "value": "123340"
        }, {
            "name": "洛扎县",
            "value": "94863"
        }, {
            "name": "隆子县",
            "value": "298916"
        }, {
            "name": "错那县",
            "value": "2411053"
        }, {
            "name": "浪卡子县",
            "value": "0"
        }],
        "2005": [{
            "name": "定日县",
            "value": "44611"
        }, {
            "name": "康马县",
            "value": "901"
        }, {
            "name": "定结县",
            "value": "26411"
        }, {
            "name": "仲巴县",
            "value": "3123"
        }, {
            "name": "亚东县",
            "value": "89821"
        }, {
            "name": "吉隆县",
            "value": "58913"
        }, {
            "name": "聂拉木县",
            "value": "26447"
        }, {
            "name": "萨嘎县",
            "value": "0"
        }, {
            "name": "岗巴县",
            "value": "0"
        }, {
            "name": "普兰县",
            "value": "2729"
        }, {
            "name": "札达县",
            "value": "0"
        }, {
            "name": "噶尔县",
            "value": "0"
        }, {
            "name": "日土县",
            "value": "0"
        }, {
            "name": "米林县",
            "value": "320442"
        }, {
            "name": "墨脱县",
            "value": "2460736"
        }, {
            "name": "察隅县",
            "value": "1885803"
        }, {
            "name": "朗县",
            "value": "123340"
        }, {
            "name": "洛扎县",
            "value": "94863"
        }, {
            "name": "隆子县",
            "value": "298916"
        }, {
            "name": "错那县",
            "value": "2411053"
        }, {
            "name": "浪卡子县",
            "value": "0"
        }],
        "2006": [{
            "name": "定日县",
            "value": "44611"
        }, {
            "name": "康马县",
            "value": "901"
        }, {
            "name": "定结县",
            "value": "26411"
        }, {
            "name": "仲巴县",
            "value": "3123"
        }, {
            "name": "亚东县",
            "value": "89821"
        }, {
            "name": "吉隆县",
            "value": "58913"
        }, {
            "name": "聂拉木县",
            "value": "26447"
        }, {
            "name": "萨嘎县",
            "value": "0"
        }, {
            "name": "岗巴县",
            "value": "0"
        }, {
            "name": "普兰县",
            "value": "2729"
        }, {
            "name": "札达县",
            "value": "0"
        }, {
            "name": "噶尔县",
            "value": "0"
        }, {
            "name": "日土县",
            "value": "0"
        }, {
            "name": "米林县",
            "value": "320442"
        }, {
            "name": "墨脱县",
            "value": "2460736"
        }, {
            "name": "察隅县",
            "value": "1885803"
        }, {
            "name": "朗县",
            "value": "123340"
        }, {
            "name": "洛扎县",
            "value": "94863"
        }, {
            "name": "隆子县",
            "value": "298916"
        }, {
            "name": "错那县",
            "value": "2411053"
        }, {
            "name": "浪卡子县",
            "value": "0"
        }],
        "2007": [{
            "name": "定日县",
            "value": "44611"
        }, {
            "name": "康马县",
            "value": "901"
        }, {
            "name": "定结县",
            "value": "26411"
        }, {
            "name": "仲巴县",
            "value": "3123"
        }, {
            "name": "亚东县",
            "value": "89821"
        }, {
            "name": "吉隆县",
            "value": "58913"
        }, {
            "name": "聂拉木县",
            "value": "26447"
        }, {
            "name": "萨嘎县",
            "value": "0"
        }, {
            "name": "岗巴县",
            "value": "0"
        }, {
            "name": "普兰县",
            "value": "2729"
        }, {
            "name": "札达县",
            "value": "0"
        }, {
            "name": "噶尔县",
            "value": "0"
        }, {
            "name": "日土县",
            "value": "0"
        }, {
            "name": "米林县",
            "value": "320442"
        }, {
            "name": "墨脱县",
            "value": "2460736"
        }, {
            "name": "察隅县",
            "value": "1885803"
        }, {
            "name": "朗县",
            "value": "123340"
        }, {
            "name": "洛扎县",
            "value": "94863"
        }, {
            "name": "隆子县",
            "value": "298916"
        }, {
            "name": "错那县",
            "value": "2411053"
        }, {
            "name": "浪卡子县",
            "value": "0"
        }],
        "2008": [{
            "name": "定日县",
            "value": "44611"
        }, {
            "name": "康马县",
            "value": "901"
        }, {
            "name": "定结县",
            "value": "26411"
        }, {
            "name": "仲巴县",
            "value": "3123"
        }, {
            "name": "亚东县",
            "value": "89821"
        }, {
            "name": "吉隆县",
            "value": "58913"
        }, {
            "name": "聂拉木县",
            "value": "26447"
        }, {
            "name": "萨嘎县",
            "value": "0"
        }, {
            "name": "岗巴县",
            "value": "0"
        }, {
            "name": "普兰县",
            "value": "2729"
        }, {
            "name": "札达县",
            "value": "0"
        }, {
            "name": "噶尔县",
            "value": "0"
        }, {
            "name": "日土县",
            "value": "0"
        }, {
            "name": "米林县",
            "value": "320442"
        }, {
            "name": "墨脱县",
            "value": "2460736"
        }, {
            "name": "察隅县",
            "value": "1885804"
        }, {
            "name": "朗县",
            "value": "123340"
        }, {
            "name": "洛扎县",
            "value": "94863"
        }, {
            "name": "隆子县",
            "value": "298916"
        }, {
            "name": "错那县",
            "value": "2411053"
        }, {
            "name": "浪卡子县",
            "value": "0"
        }],
        "2009": [{
            "name": "定日县",
            "value": "44611"
        }, {
            "name": "康马县",
            "value": "901"
        }, {
            "name": "定结县",
            "value": "26411"
        }, {
            "name": "仲巴县",
            "value": "3123"
        }, {
            "name": "亚东县",
            "value": "89821"
        }, {
            "name": "吉隆县",
            "value": "58913"
        }, {
            "name": "聂拉木县",
            "value": "26447"
        }, {
            "name": "萨嘎县",
            "value": "0"
        }, {
            "name": "岗巴县",
            "value": "0"
        }, {
            "name": "普兰县",
            "value": "2729"
        }, {
            "name": "札达县",
            "value": "0"
        }, {
            "name": "噶尔县",
            "value": "0"
        }, {
            "name": "日土县",
            "value": "0"
        }, {
            "name": "米林县",
            "value": "320442"
        }, {
            "name": "墨脱县",
            "value": "2460736"
        }, {
            "name": "察隅县",
            "value": "1885804"
        }, {
            "name": "朗县",
            "value": "123340"
        }, {
            "name": "洛扎县",
            "value": "94863"
        }, {
            "name": "隆子县",
            "value": "298916"
        }, {
            "name": "错那县",
            "value": "2411053"
        }, {
            "name": "浪卡子县",
            "value": "0"
        }],
        "2010": [{
            "name": "定日县",
            "value": "44611"
        }, {
            "name": "康马县",
            "value": "901"
        }, {
            "name": "定结县",
            "value": "26411"
        }, {
            "name": "仲巴县",
            "value": "3123"
        }, {
            "name": "亚东县",
            "value": "89821"
        }, {
            "name": "吉隆县",
            "value": "58913"
        }, {
            "name": "聂拉木县",
            "value": "26447"
        }, {
            "name": "萨嘎县",
            "value": "0"
        }, {
            "name": "岗巴县",
            "value": "0"
        }, {
            "name": "普兰县",
            "value": "2729"
        }, {
            "name": "札达县",
            "value": "0"
        }, {
            "name": "噶尔县",
            "value": "0"
        }, {
            "name": "日土县",
            "value": "0"
        }, {
            "name": "米林县",
            "value": "320442"
        }, {
            "name": "墨脱县",
            "value": "2460736"
        }, {
            "name": "察隅县",
            "value": "1885804"
        }, {
            "name": "朗县",
            "value": "123340"
        }, {
            "name": "洛扎县",
            "value": "94863"
        }, {
            "name": "隆子县",
            "value": "298916"
        }, {
            "name": "错那县",
            "value": "2411053"
        }, {
            "name": "浪卡子县",
            "value": "0"
        }],
        "2011": [{
            "name": "定日县",
            "value": "44611"
        }, {
            "name": "康马县",
            "value": "901"
        }, {
            "name": "定结县",
            "value": "26411"
        }, {
            "name": "仲巴县",
            "value": "3175"
        }, {
            "name": "亚东县",
            "value": "89813"
        }, {
            "name": "吉隆县",
            "value": "58913"
        }, {
            "name": "聂拉木县",
            "value": "26446"
        }, {
            "name": "萨嘎县",
            "value": "0"
        }, {
            "name": "岗巴县",
            "value": "0"
        }, {
            "name": "普兰县",
            "value": "2729"
        }, {
            "name": "札达县",
            "value": "0"
        }, {
            "name": "噶尔县",
            "value": "0"
        }, {
            "name": "日土县",
            "value": "0"
        }, {
            "name": "米林县",
            "value": "320422"
        }, {
            "name": "墨脱县",
            "value": "2460561"
        }, {
            "name": "察隅县",
            "value": "1885763"
        }, {
            "name": "朗县",
            "value": "123340"
        }, {
            "name": "洛扎县",
            "value": "94863"
        }, {
            "name": "隆子县",
            "value": "298916"
        }, {
            "name": "错那县",
            "value": "2410991"
        }, {
            "name": "浪卡子县",
            "value": "0"
        }],
        "2012": [{
            "name": "定日县",
            "value": "44611"
        }, {
            "name": "康马县",
            "value": "901"
        }, {
            "name": "定结县",
            "value": "26411"
        }, {
            "name": "仲巴县",
            "value": "3227"
        }, {
            "name": "亚东县",
            "value": "89805"
        }, {
            "name": "吉隆县",
            "value": "58913"
        }, {
            "name": "聂拉木县",
            "value": "26446"
        }, {
            "name": "萨嘎县",
            "value": "0"
        }, {
            "name": "岗巴县",
            "value": "0"
        }, {
            "name": "普兰县",
            "value": "2729"
        }, {
            "name": "札达县",
            "value": "0"
        }, {
            "name": "噶尔县",
            "value": "0"
        }, {
            "name": "日土县",
            "value": "0"
        }, {
            "name": "米林县",
            "value": "320402"
        }, {
            "name": "墨脱县",
            "value": "2460386"
        }, {
            "name": "察隅县",
            "value": "1885722"
        }, {
            "name": "朗县",
            "value": "123340"
        }, {
            "name": "洛扎县",
            "value": "94863"
        }, {
            "name": "隆子县",
            "value": "298916"
        }, {
            "name": "错那县",
            "value": "2410928"
        }, {
            "name": "浪卡子县",
            "value": "0"
        }],
        "2013": [{
            "name": "定日县",
            "value": "44611"
        }, {
            "name": "康马县",
            "value": "901"
        }, {
            "name": "定结县",
            "value": "26411"
        }, {
            "name": "仲巴县",
            "value": "3280"
        }, {
            "name": "亚东县",
            "value": "89798"
        }, {
            "name": "吉隆县",
            "value": "58913"
        }, {
            "name": "聂拉木县",
            "value": "26445"
        }, {
            "name": "萨嘎县",
            "value": "0"
        }, {
            "name": "岗巴县",
            "value": "0"
        }, {
            "name": "普兰县",
            "value": "2729"
        }, {
            "name": "札达县",
            "value": "0"
        }, {
            "name": "噶尔县",
            "value": "0"
        }, {
            "name": "日土县",
            "value": "0"
        }, {
            "name": "米林县",
            "value": "320381"
        }, {
            "name": "墨脱县",
            "value": "2460212"
        }, {
            "name": "察隅县",
            "value": "1885682"
        }, {
            "name": "朗县",
            "value": "123340"
        }, {
            "name": "洛扎县",
            "value": "94863"
        }, {
            "name": "隆子县",
            "value": "298916"
        }, {
            "name": "错那县",
            "value": "2410866"
        }, {
            "name": "浪卡子县",
            "value": "0"
        }],
        "2014": [{
            "name": "定日县",
            "value": "44611"
        }, {
            "name": "康马县",
            "value": "901"
        }, {
            "name": "定结县",
            "value": "26411"
        }, {
            "name": "仲巴县",
            "value": "3332"
        }, {
            "name": "亚东县",
            "value": "89790"
        }, {
            "name": "吉隆县",
            "value": "58913"
        }, {
            "name": "聂拉木县",
            "value": "26445"
        }, {
            "name": "萨嘎县",
            "value": "0"
        }, {
            "name": "岗巴县",
            "value": "0"
        }, {
            "name": "普兰县",
            "value": "2729"
        }, {
            "name": "札达县",
            "value": "0"
        }, {
            "name": "噶尔县",
            "value": "0"
        }, {
            "name": "日土县",
            "value": "0"
        }, {
            "name": "米林县",
            "value": "320361"
        }, {
            "name": "墨脱县",
            "value": "2460037"
        }, {
            "name": "察隅县",
            "value": "1885641"
        }, {
            "name": "朗县",
            "value": "123340"
        }, {
            "name": "洛扎县",
            "value": "94863"
        }, {
            "name": "隆子县",
            "value": "298916"
        }, {
            "name": "错那县",
            "value": "2410803"
        }, {
            "name": "浪卡子县",
            "value": "0"
        }],
        "2015": [{
            "name": "定日县",
            "value": "44611"
        }, {
            "name": "康马县",
            "value": "901"
        }, {
            "name": "定结县",
            "value": "26411"
        }, {
            "name": "仲巴县",
            "value": "3384"
        }, {
            "name": "亚东县",
            "value": "89782"
        }, {
            "name": "吉隆县",
            "value": "58913"
        }, {
            "name": "聂拉木县",
            "value": "26444"
        }, {
            "name": "萨嘎县",
            "value": "0"
        }, {
            "name": "岗巴县",
            "value": "0"
        }, {
            "name": "普兰县",
            "value": "2729"
        }, {
            "name": "札达县",
            "value": "0"
        }, {
            "name": "噶尔县",
            "value": "0"
        }, {
            "name": "日土县",
            "value": "0"
        }, {
            "name": "米林县",
            "value": "320341"
        }, {
            "name": "墨脱县",
            "value": "2459862"
        }, {
            "name": "察隅县",
            "value": "1885600"
        }, {
            "name": "朗县",
            "value": "123340"
        }, {
            "name": "洛扎县",
            "value": "94863"
        }, {
            "name": "隆子县",
            "value": "298916"
        }, {
            "name": "错那县",
            "value": "2410741"
        }, {
            "name": "浪卡子县",
            "value": "0"
        }]
    }
];

